platform:
  datasource:
    writer:
      url: ${DB_WRITER_URL}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
    reader:
      url: ${DB_READER_URL:}
      username: ${DB_READER_USERNAME:${DB_USERNAME}}
      password: ${DB_READER_PASSWORD:${DB_PASSWORD}}
