platform:
  security:
    enabled: ${SECURITY_ENABLED}
  datasource:
    writer:
      url: ${DB_WRITER_URL}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
    reader:
      url: ${DB_READER_URL:}
      username: ${DB_READER_USERNAME:${DB_USERNAME}}
      password: ${DB_READER_PASSWORD:${DB_PASSWORD}}

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OIDC_ISSUER_URI}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      username: ${REDIS_USERNAME:}
      password: ${REDIS_PASSWORD}
      ssl:
        enabled: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    security:
      protocol: ${KAFKA_SECURITY_PROTOCOL}
    producer:
      properties:
        enable.idempotence: true
        acks: all
  elasticsearch:
    uris: ${ELASTICSEARCH_URIS}
    username: ${ELASTICSEARCH_USERNAME}
    password: ${ELASTICSEARCH_PASSWORD}

management:
  endpoint:
    health:
      show-details: never
